[package]
authors = ["Tamo <tamo@meilisearch.com", "Dean Karn <dean@segment.com>", "Ulysse Carion <ulysse@segment.com>"]
description = "Segment analytics client for Rust. Forked for [Meilisearch](https://github.com/meilisearch)"
edition = "2018"
license = "MIT"
keywords = ["meilisearch", "analytics", "segment"]
name = "segment"
version = "0.1.0"
readme = "README.md"

[dependencies]
async-trait = "0.1.51"
chrono = { version = "0.4.19", features = ["serde"] }
reqwest = { version = "0.11.4", features = ["rustls-tls", "json"], default-features = false }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
thiserror = "1.0.29"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"], default-features = false }
