[package]
authors = ["Dean Karn <dean@segment.com>","Ulysse Carion <ulysse@segment.com>"]
description = "Segment analytics client for Rust https://segment.com/docs/libraries/rust"
edition = "2018"
license = "MIT"
name = "segment"
version = "0.2.0"
readme = "README.md"

[[bin]]
name = "analytics"
path = "src/main.rs"
required-features = ["cli"]

[dependencies]
async-trait = "0.1.51"
failure = "0.1.5"
reqwest = { version = "0.11.4", features = ["rustls-tls", "json"], default-features = false }
serde_json = "1.0.68"
chrono = { version = "0.4.6", features = ["serde"] }
clap = { version = "2.33", optional = true }
serde = { version = "1.0.130", features = ["derive"] }

[features]
cli = ["clap"]
